# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.20.6
neo_version=20.6.115
neogradle.subsystems.parchment.minecraftVersion=1.20.6
neogradle.subsystems.parchment.mappingsVersion=2024.06.02
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
mod_group=com.mrbysco.limbs
mod_id=limbs
mod_archive_name=Limbs

#Publishing
mod_name=Limbs
curseforge_id=627878
modrinth_id=EGCNABjL

# Version
version=4.0.0

# Dependencies
jei_version=18.0.0.65
curios_version=8.0.1
heads_version=1.20.6:1.1.2
fivehead_version=1.20.5:5.0.0