modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Mrbysco/limbs/issues"
license="MIT"

[[mods]]
modId="limbs"
version="${file.jarVersion}"
displayName="Limbs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/limbs"
authors="Mrbysco"
description='''
I read a book about limbs taking over the world

It was armageddon
'''
[[dependencies.limbs]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.limbs]]
modId="curios"
mandatory=true
versionRange="[1.19.1-5.1.0.5,]"
ordering="NONE"
side="BOTH"