modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/limbs/issues"
license="MIT"

[[mods]]
modId="limbs"
version="${file.jarVersion}"
displayName="Limbs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/limbs"
authors="Mrbysco"
description='''
I read a book about limbs taking over the world

It was armageddon
'''
[[dependencies.limbs]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.limbs]]
modId="curios"
mandatory=true
versionRange="[6.1.0+1.20.2,]"
ordering="NONE"
side="BOTH"
[[mixins]]
config="limbs.mixins.json"