modLoader="javafml"
loaderVersion="[3,)"
issueTrackerURL="https://github.com/Mrbysco/limbs/issues"
license="MIT"

[[mods]]
modId="limbs"
version="${file.jarVersion}"
displayName="Limbs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/limbs"
authors="Mrbysco"
description='''
I read a book about limbs taking over the world

It was armageddon
'''
[[dependencies.limbs]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.limbs]]
modId="curios"
type="REQUIRED"
versionRange="[8.0.1+1.20.6,]"
ordering="NONE"
side="BOTH"
[[mixins]]
config="limbs.mixins.json"