package com.mrbysco.limbs.registry;

import com.mrbysco.limbs.Limbs;
import com.mrbysco.limbs.client.bodypart.BodyPartRegistry;
import com.mrbysco.limbs.client.bodypart.BodyPartType;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.geom.ModelLayers;
import net.minecraft.client.model.monster.enderman.EndermanModel;
import net.minecraft.client.model.monster.piglin.AdultPiglinModel;
import net.minecraft.client.model.monster.skeleton.SkeletonModel;
import net.minecraft.client.model.monster.zombie.ZombieModel;
import net.minecraft.resources.Identifier;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class PartRegistry {
	public static final DeferredRegister<BodyPartType> BODY_PARTS = DeferredRegister.create(BodyPartRegistry.BODY_PARTS_KEY, Limbs.MOD_ID);

	public static final DeferredHolder<BodyPartType, BodyPartType> SKELETON_HEAD = BODY_PARTS.register("skeleton_head", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.SKELETON)).getHead(), Identifier.withDefaultNamespace("textures/entity/skeleton/skeleton.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> SKELETON_TORSO = BODY_PARTS.register("skeleton_torso", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.SKELETON)).body, Identifier.withDefaultNamespace("textures/entity/skeleton/skeleton.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> SKELETON_LEFT_ARM = BODY_PARTS.register("skeleton_left_arm", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.SKELETON)).leftArm, Identifier.withDefaultNamespace("textures/entity/skeleton/skeleton.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> SKELETON_RIGHT_ARM = BODY_PARTS.register("skeleton_right_arm", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.SKELETON)).rightArm, Identifier.withDefaultNamespace("textures/entity/skeleton/skeleton.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> SKELETON_LEFT_LEG = BODY_PARTS.register("skeleton_left_leg", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.SKELETON)).leftLeg, Identifier.withDefaultNamespace("textures/entity/skeleton/skeleton.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> SKELETON_RIGHT_LEG = BODY_PARTS.register("skeleton_right_leg", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.SKELETON)).rightLeg, Identifier.withDefaultNamespace("textures/entity/skeleton/skeleton.png")));

	public static final DeferredHolder<BodyPartType, BodyPartType> STRAY_HEAD = BODY_PARTS.register("stray_head", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.STRAY)).getHead(), Identifier.withDefaultNamespace("textures/entity/skeleton/stray.png"), Identifier.withDefaultNamespace("textures/entity/skeleton/stray_overlay.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> STRAY_TORSO = BODY_PARTS.register("stray_torso", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.STRAY)).body, Identifier.withDefaultNamespace("textures/entity/skeleton/stray.png"), Identifier.withDefaultNamespace("textures/entity/skeleton/stray_overlay.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> STRAY_LEFT_ARM = BODY_PARTS.register("stray_left_arm", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.STRAY)).leftArm, Identifier.withDefaultNamespace("textures/entity/skeleton/stray.png"), Identifier.withDefaultNamespace("textures/entity/skeleton/stray_overlay.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> STRAY_RIGHT_ARM = BODY_PARTS.register("stray_right_arm", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.STRAY)).rightArm, Identifier.withDefaultNamespace("textures/entity/skeleton/stray.png"), Identifier.withDefaultNamespace("textures/entity/skeleton/stray_overlay.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> STRAY_LEFT_LEG = BODY_PARTS.register("stray_left_leg", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.STRAY)).leftLeg, Identifier.withDefaultNamespace("textures/entity/skeleton/stray.png"), Identifier.withDefaultNamespace("textures/entity/skeleton/stray_overlay.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> STRAY_RIGHT_LEG = BODY_PARTS.register("stray_right_leg", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.STRAY)).rightLeg, Identifier.withDefaultNamespace("textures/entity/skeleton/stray.png"), Identifier.withDefaultNamespace("textures/entity/skeleton/stray_overlay.png")));

	public static final DeferredHolder<BodyPartType, BodyPartType> WITHER_SKELETON_HEAD = BODY_PARTS.register("wither_skeleton_head", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.WITHER_SKELETON)).getHead(), Identifier.withDefaultNamespace("textures/entity/skeleton/wither_skeleton.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> WITHER_SKELETON_TORSO = BODY_PARTS.register("wither_skeleton_torso", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.WITHER_SKELETON)).body, Identifier.withDefaultNamespace("textures/entity/skeleton/wither_skeleton.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> WITHER_SKELETON_LEFT_ARM = BODY_PARTS.register("wither_skeleton_left_arm", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.WITHER_SKELETON)).leftArm, Identifier.withDefaultNamespace("textures/entity/skeleton/wither_skeleton.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> WITHER_SKELETON_RIGHT_ARM = BODY_PARTS.register("wither_skeleton_right_arm", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.WITHER_SKELETON)).rightArm, Identifier.withDefaultNamespace("textures/entity/skeleton/wither_skeleton.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> WITHER_SKELETON_LEFT_LEG = BODY_PARTS.register("wither_skeleton_left_leg", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.WITHER_SKELETON)).leftLeg, Identifier.withDefaultNamespace("textures/entity/skeleton/wither_skeleton.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> WITHER_SKELETON_RIGHT_LEG = BODY_PARTS.register("wither_skeleton_right_leg", () -> new BodyPartType(() -> new SkeletonModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.WITHER_SKELETON)).rightLeg, Identifier.withDefaultNamespace("textures/entity/skeleton/wither_skeleton.png")));

	public static final DeferredHolder<BodyPartType, BodyPartType> ZOMBIE_HEAD = BODY_PARTS.register("zombie_head", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ZOMBIE)).getHead(), Identifier.withDefaultNamespace("textures/entity/zombie/zombie.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ZOMBIE_TORSO = BODY_PARTS.register("zombie_torso", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ZOMBIE)).body, Identifier.withDefaultNamespace("textures/entity/zombie/zombie.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ZOMBIE_LEFT_ARM = BODY_PARTS.register("zombie_left_arm", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ZOMBIE)).leftArm, Identifier.withDefaultNamespace("textures/entity/zombie/zombie.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ZOMBIE_RIGHT_ARM = BODY_PARTS.register("zombie_right_arm", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ZOMBIE)).rightArm, Identifier.withDefaultNamespace("textures/entity/zombie/zombie.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ZOMBIE_LEFT_LEG = BODY_PARTS.register("zombie_left_leg", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ZOMBIE)).leftLeg, Identifier.withDefaultNamespace("textures/entity/zombie/zombie.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ZOMBIE_RIGHT_LEG = BODY_PARTS.register("zombie_right_leg", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ZOMBIE)).rightLeg, Identifier.withDefaultNamespace("textures/entity/zombie/zombie.png")));

	public static final DeferredHolder<BodyPartType, BodyPartType> HUSK_HEAD = BODY_PARTS.register("husk_head", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.HUSK)).getHead(), Identifier.withDefaultNamespace("textures/entity/zombie/husk.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> HUSK_TORSO = BODY_PARTS.register("husk_torso", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.HUSK)).body, Identifier.withDefaultNamespace("textures/entity/zombie/husk.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> HUSK_LEFT_ARM = BODY_PARTS.register("husk_left_arm", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.HUSK)).leftArm, Identifier.withDefaultNamespace("textures/entity/zombie/husk.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> HUSK_RIGHT_ARM = BODY_PARTS.register("husk_right_arm", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.HUSK)).rightArm, Identifier.withDefaultNamespace("textures/entity/zombie/husk.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> HUSK_LEFT_LEG = BODY_PARTS.register("husk_left_leg", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.HUSK)).leftLeg, Identifier.withDefaultNamespace("textures/entity/zombie/husk.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> HUSK_RIGHT_LEG = BODY_PARTS.register("husk_right_leg", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.HUSK)).rightLeg, Identifier.withDefaultNamespace("textures/entity/zombie/husk.png")));

	public static final DeferredHolder<BodyPartType, BodyPartType> DROWNED_HEAD = BODY_PARTS.register("drowned_head", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.DROWNED)).getHead(), Identifier.withDefaultNamespace("textures/entity/zombie/drowned.png"), Identifier.withDefaultNamespace("textures/entity/zombie/drowned_outer_layer.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> DROWNED_TORSO = BODY_PARTS.register("drowned_torso", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.DROWNED)).body, Identifier.withDefaultNamespace("textures/entity/zombie/drowned.png"), Identifier.withDefaultNamespace("textures/entity/zombie/drowned_outer_layer.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> DROWNED_LEFT_ARM = BODY_PARTS.register("drowned_left_arm", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.DROWNED)).leftArm, Identifier.withDefaultNamespace("textures/entity/zombie/drowned.png"), Identifier.withDefaultNamespace("textures/entity/zombie/drowned_outer_layer.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> DROWNED_RIGHT_ARM = BODY_PARTS.register("drowned_right_arm", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.DROWNED)).rightArm, Identifier.withDefaultNamespace("textures/entity/zombie/drowned.png"), Identifier.withDefaultNamespace("textures/entity/zombie/drowned_outer_layer.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> DROWNED_LEFT_LEG = BODY_PARTS.register("drowned_left_leg", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.DROWNED)).leftLeg, Identifier.withDefaultNamespace("textures/entity/zombie/drowned.png"), Identifier.withDefaultNamespace("textures/entity/zombie/drowned_outer_layer.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> DROWNED_RIGHT_LEG = BODY_PARTS.register("drowned_right_leg", () -> new BodyPartType(() -> new ZombieModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.DROWNED)).rightLeg, Identifier.withDefaultNamespace("textures/entity/zombie/drowned.png"), Identifier.withDefaultNamespace("textures/entity/zombie/drowned_outer_layer.png")));

	public static final DeferredHolder<BodyPartType, BodyPartType> ENDERMAN_HEAD = BODY_PARTS.register("enderman_head", () -> new BodyPartType(() -> new EndermanModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ENDERMAN)).getHead(), Identifier.withDefaultNamespace("textures/entity/enderman/enderman.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ENDERMAN_TORSO = BODY_PARTS.register("enderman_torso", () -> new BodyPartType(() -> new EndermanModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ENDERMAN)).body, Identifier.withDefaultNamespace("textures/entity/enderman/enderman.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ENDERMAN_LEFT_ARM = BODY_PARTS.register("enderman_left_arm", () -> new BodyPartType(() -> new EndermanModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ENDERMAN)).leftArm, Identifier.withDefaultNamespace("textures/entity/enderman/enderman.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ENDERMAN_RIGHT_ARM = BODY_PARTS.register("enderman_right_arm", () -> new BodyPartType(() -> new EndermanModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ENDERMAN)).rightArm, Identifier.withDefaultNamespace("textures/entity/enderman/enderman.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ENDERMAN_LEFT_LEG = BODY_PARTS.register("enderman_left_leg", () -> new BodyPartType(() -> new EndermanModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ENDERMAN)).leftLeg, Identifier.withDefaultNamespace("textures/entity/enderman/enderman.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ENDERMAN_RIGHT_LEG = BODY_PARTS.register("enderman_right_leg", () -> new BodyPartType(() -> new EndermanModel<>(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ENDERMAN)).rightLeg, Identifier.withDefaultNamespace("textures/entity/enderman/enderman.png")));

	public static final DeferredHolder<BodyPartType, BodyPartType> PIGLIN_HEAD = BODY_PARTS.register("piglin_head", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.PIGLIN)).getHead(), Identifier.withDefaultNamespace("textures/entity/piglin/piglin.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> PIGLIN_TORSO = BODY_PARTS.register("piglin_torso", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.PIGLIN)).body, Identifier.withDefaultNamespace("textures/entity/piglin/piglin.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> PIGLIN_LEFT_ARM = BODY_PARTS.register("piglin_left_arm", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.PIGLIN)).leftArm, Identifier.withDefaultNamespace("textures/entity/piglin/piglin.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> PIGLIN_RIGHT_ARM = BODY_PARTS.register("piglin_right_arm", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.PIGLIN)).rightArm, Identifier.withDefaultNamespace("textures/entity/piglin/piglin.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> PIGLIN_LEFT_LEG = BODY_PARTS.register("piglin_left_leg", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.PIGLIN)).leftLeg, Identifier.withDefaultNamespace("textures/entity/piglin/piglin.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> PIGLIN_RIGHT_LEG = BODY_PARTS.register("piglin_right_leg", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.PIGLIN)).rightLeg, Identifier.withDefaultNamespace("textures/entity/piglin/piglin.png")));

	public static final DeferredHolder<BodyPartType, BodyPartType> ZOMBIFIED_PIGLIN_HEAD = BODY_PARTS.register("zombified_piglin_head", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ZOMBIFIED_PIGLIN)).getHead(), Identifier.withDefaultNamespace("textures/entity/piglin/zombified_piglin.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ZOMBIFIED_PIGLIN_TORSO = BODY_PARTS.register("zombified_piglin_torso", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ZOMBIFIED_PIGLIN)).body, Identifier.withDefaultNamespace("textures/entity/piglin/zombified_piglin.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ZOMBIFIED_PIGLIN_LEFT_ARM = BODY_PARTS.register("zombified_piglin_left_arm", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ZOMBIFIED_PIGLIN)).leftArm, Identifier.withDefaultNamespace("textures/entity/piglin/zombified_piglin.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ZOMBIFIED_PIGLIN_RIGHT_ARM = BODY_PARTS.register("zombified_piglin_right_arm", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ZOMBIFIED_PIGLIN)).rightArm, Identifier.withDefaultNamespace("textures/entity/piglin/zombified_piglin.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ZOMBIFIED_PIGLIN_LEFT_LEG = BODY_PARTS.register("zombified_piglin_left_leg", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ZOMBIFIED_PIGLIN)).leftLeg, Identifier.withDefaultNamespace("textures/entity/piglin/zombified_piglin.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> ZOMBIFIED_PIGLIN_RIGHT_LEG = BODY_PARTS.register("zombified_piglin_right_leg", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.ZOMBIFIED_PIGLIN)).rightLeg, Identifier.withDefaultNamespace("textures/entity/piglin/zombified_piglin.png")));

	public static final DeferredHolder<BodyPartType, BodyPartType> PIGLIN_BRUTE_HEAD = BODY_PARTS.register("piglin_brute_head", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.PIGLIN_BRUTE)).getHead(), Identifier.withDefaultNamespace("textures/entity/piglin/piglin_brute.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> PIGLIN_BRUTE_TORSO = BODY_PARTS.register("piglin_brute_torso", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.PIGLIN_BRUTE)).body, Identifier.withDefaultNamespace("textures/entity/piglin/piglin_brute.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> PIGLIN_BRUTE_LEFT_ARM = BODY_PARTS.register("piglin_brute_left_arm", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.PIGLIN_BRUTE)).leftArm, Identifier.withDefaultNamespace("textures/entity/piglin/piglin_brute.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> PIGLIN_BRUTE_RIGHT_ARM = BODY_PARTS.register("piglin_brute_right_arm", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.PIGLIN_BRUTE)).rightArm, Identifier.withDefaultNamespace("textures/entity/piglin/piglin_brute.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> PIGLIN_BRUTE_LEFT_LEG = BODY_PARTS.register("piglin_brute_left_leg", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.PIGLIN_BRUTE)).leftLeg, Identifier.withDefaultNamespace("textures/entity/piglin/piglin_brute.png")));
	public static final DeferredHolder<BodyPartType, BodyPartType> PIGLIN_BRUTE_RIGHT_LEG = BODY_PARTS.register("piglin_brute_right_leg", () -> new BodyPartType(() -> new AdultPiglinModel(Minecraft.getInstance().getEntityModels().bakeLayer(ModelLayers.PIGLIN_BRUTE)).rightLeg, Identifier.withDefaultNamespace("textures/entity/piglin/piglin_brute.png")));
}
